### PR TITLE
Continue installing recipes if cleanup recipe failed

### PR DESCRIPTION
**Pull request by MohanDV**
If the script is running for the first time or if any of the recipe is manually deleted then the recipe.sh will fail to install the recipes.

### CODE REVIEW

**Review by simonellistonball — APPROVED** [review]

**Comment by MohanDV** [comment]
@simonellistonball can you please merge this

**Review by simonellistonball — APPROVED** [review]

**Comment by simonellistonball** [comment]
Could you de-conflict @MohanDV

**Comment by MohanDV** [comment]
Sure Simon , Thanks !!

**Comment by MohanDV** [comment]
> Could you de-conflict @MohanDV

done @simonellistonball

**Pull request merged**
